### PR TITLE
Allow streaming upload as opposed to multipart upload

### PR DESCRIPTION
**Pull request by koen-serry**

### CODE REVIEW

**Comment by furver** [comment]
+1 I would love to see that too! :)
Any progress ?

**Comment by daric81** [comment]
+1
I like this library, but its doesn't seem to be getting any dev time recently. I might jump to an alternative that is being more actively developed.

**Comment by sunshineo** [comment]
+1 for this
@daric81 Which other library is being more actively developed?

**Comment by daric81** [comment]
@sunshineo 

Still using this library with multipart upload at present. I noticed danialfarid / angular-file-upload project is getting regular activity so might be worth using instead.

**Comment by sunshineo** [comment]
Thanks @daric81 ! I tried that one. By default it is also assuming multipart but it is able to do stream.

**Comment by koen-serry** [comment]
This is a bit silly as it only adds functionality without any extra complexity. Since so many people are asking for it. Original author lost interest I guess.

**Comment by sunshineo** [comment]
@koen-serry  We guess so. I'm also wondering if we should have multi-part upload and stream upload just as 2 completely separated library.

**Comment by nervgh** [comment]
releated #275

**Comment by nervgh** [comment]
https://github.com/nervgh/angular-file-upload/pull/602

> Original author lost interest I guess

I have many private parallel projects and I have not enough time for support all my open source projects. Sorry, guys :flushed: 
Moreover [that](https://github.com/nervgh/angular-file-upload/issues/622#issuecomment-217724215)

**Comment by nervgh** [comment]
Thanks for your effort anyway :+1:

**Pull request closed without merging**
