### PR TITLE
Add ability to cancel an update in the onBeforeUploadItem event

### PR DESCRIPTION
**Pull request by mrpmorris**
This enables the consumer of the onBeforeUploadItem event to cancel the upload just at the point it is about to be uploaded. This is useful for checking conditions at the point of upload which may have changed from the point it was added to the queue.

By default the result of onBeforeUploadItem will return true, causing the library to act in exactly the same way it does now - if the event handler returns false then the update is cancelled.

### CODE REVIEW

**Comment by mrpmorris** [comment]
How do I know when/if this is merged into branch, will github email me or anything?

**Comment by nervgh** [comment]
Thank you!

Looks like the diff very big https://github.com/nervgh/angular-file-upload/pull/624/commits/649c62bd089ae073fa36021d7c8bea21b69d3716#diff-52bbcc9546e5ba6702743aad877b3f4f

What you think about this?
```js
/**
 * The XMLHttpRequest transport
 * @param {FileItem} item
 * @private
 */
_xhrTransport(item) {
    var xhr = item._xhr = new XMLHttpRequest();
    var form = new FormData();

    if (this._onBeforeUploadItem(item)) {
        this._onCancelItem(item);
        this._onCompleteItem(item);
        return;
    }
```

```js
/**
 * Uploads a item from the queue
 * @param {FileItem|Number} value
 */
uploadItem(value) {
   // ...
   this[transport](item);
   this._render(); // <--
}
```

**Comment by mrpmorris** [comment]
That looks like it will work :)

Do you want/need me to do anything, or do you intend just to change it yourself ?

**Comment by nervgh** [comment]
Please
1. decrease difference size of your PR if it possible
2. remove [bundled](https://github.com/nervgh/angular-file-upload/pull/602#issuecomment-217903053) files from your PR

**Comment by nervgh** [comment]
#425

**Pull request closed without merging**
