### PR TITLE
Feature - add support for asynchronous filters

### PR DESCRIPTION
**Pull request by brownbathrobe**
r? @nervgh 

related to https://github.com/nervgh/angular-file-upload/issues/235 & https://github.com/nervgh/angular-file-upload/issues/180

### CODE REVIEW

**Comment by kuntsali** [comment]
@brownbathrobe Hi, brownbathrobe! I want to use your changes in pull request to implement height and width filter. Can you provide some example of filter usage or it can be used as usual? Thanks

**Comment by brownbathrobe** [comment]
@kuntsali - You should be able to use the filters as normal, but in the case of height/width you'll want the filter to return a promise. Here's an example that filters out folders:

```javascript
uploader.filters.push({
  name: "rejectFolder",
  fn: function (item) {
    var deferred = $q.defer();
    function accept () { deferred.resolve(); }
    function reject () { deferred.reject(); }

    if (uploader.isHTML5) {
      var reader = new FileReader();
      /* file can be read successfully */
      reader.onloadstart = function () {
        accept();
        reader.onerror = null;
        reader.abort();
      };
      /* file can not be read and is likely a folder */
      reader.onerror = function () {
        reject();
      };
      /* try to read the file item */
      reader.readAsArrayBuffer(item);
    } else {
      accept();
    }
    return deferred.promise;
  }
});
```

**Comment by kuntsali** [comment]
@brownbathrobe - Thank you!

**Comment by markslemko** [comment]
+1

**Comment by nervgh** [comment]
Now we can use sync and async filters. See [an example](https://github.com/nervgh/angular-file-upload/blob/master/examples/simple/controllers.js#L15).

**Pull request closed without merging**
