### PR TITLE
Callbacks for removing item and clearing queue

### PR DESCRIPTION
**Pull request by bkowalik**
I have this problem that I use this module to upload files asynchronously to my server. But I also update model in angular that holds info about what was uploaded and some additional data. But when it comes to removing items I have to override in place (hack) library to update my model that some item is no longer used. So I wrote this code:

```
$scope.uploader.onSuccessItem = function(item, response, status, headers) {
    var file = $scope.someModel.update(response.someData);
    file.fileName = item.file.name;
    file.contentType = item.file.type;

    item.remove = function() {
        $scope.someModel.removeFile(response.someData);
        return $scope.uploader.removeFromQueue(item);
    }
};
```

But this is based on internal implementation of `FileItem.remove()` what is ugly. In my PR I have written two callback. First `FileUploader.onRemoveFromQueue(item)` is launched before deleting an item so you still have some information about it. Second one `FileUploader.onClearQueue()` is fired when clearing queue was clicked. It's pretty annoying that removing callbacks are missing. BTW, I saw PR  #283

### CODE REVIEW

**Comment by bkowalik** [comment]
@nervgh

**Comment by nervgh** [comment]
@bkowalik , see https://github.com/nervgh/angular-file-upload/pull/283#issuecomment-125481170

**Comment by bkowalik** [comment]
@nervgh , I have made some clean ups and added callback for ```{FileItem}```

**Comment by mkeremguc** [comment]
bump

**Pull request closed without merging**
