### PR TITLE
Handle "file is no longer valid" errors

### PR DESCRIPTION
**Pull request by darrylkuhn**
In some cases the file object can become invalid. For example if the user is uploading off a USB stick and removes the disk mid-upload. At that point the File object no longer has a valid reference to the file on disk. This pull request helps to gracefully handle those cases.

### CODE REVIEW

**Comment by nervgh** [comment]
[This](https://github.com/darrylkuhn/angular-file-upload/commit/79c9c49efec3f91e6b669d93e97dff538c616eb5#diff-47426efabbdf4a14eefdc36d3a774fc0L799) code don't be work if I say
```js
uploader.uploadItem(item);
```
[API](https://github.com/nervgh/angular-file-upload/wiki/Module-API#methods)

**Comment by darrylkuhn** [comment]
@nervgh I tried to test it in my code base and was able to call `uploader.uploadItem(item);` successfully. How are you getting a failure?

**Comment by darrylkuhn** [comment]
Just poking at this again to see if there is something I can/should do here...

**Comment by nervgh** [comment]
@darrylkuhn, you're right. I'm sorry for the delay.

**Comment by darrylkuhn** [comment]
@nervgh no worries - I know real-life can get in the way of these sorts of things. Thanks for all the work building / maintaining the angular-file-upload project!

**Comment by nervgh** [comment]
@darrylkuhn , thank you for understanding. I will be glad to your participation in this project in the future =)

**Pull request merged**
