### PR TITLE
Fixes nv-file-select reset bug when queued 

### PR DESCRIPTION
**Pull request by denkan**
The current `el.replaceWith( el.clone(this) )` drops the change-event (even though it should deep clone?). This cause the file picker to stop working after adding the first file(s). 

Fixed by replace its element with re-$compile'd self.

### CODE REVIEW

**Comment by itamair** [comment]
Tnx. This works for me ... Now I am able to use input multiple to add, remove and re-add new files ... more than once. Hope will be took into consideration for a master merge

**Comment by nervgh** [comment]
@denkan , thank you! Please, see [that](https://github.com/nervgh/angular-file-upload/pull/602#issuecomment-217719729) comment.

**Comment by denkan** [comment]
Sorry for late action. 
Removed dist files from PR.

**Comment by nervgh** [comment]
@denkan , thank you :+1:

**Pull request merged**
