### PR TITLE
A fix for OnDragLeave causing a flickering affect

### PR DESCRIPTION
**Pull request by rylan**
Fixed flickering effect being caused with the addition and removal of the overclass on drag. When OnDragLeave event triggers the logic should be if the two elements are not the same remove the over class, otherwise return.

### CODE REVIEW

**Comment by nervgh** [comment]
Fixed 9c584b232b98f2e1d691d206c42a7c5160fcdefe. Thanks, guys :+1:

**Comment by jackhsu978** [comment]
@rylan I have the same issue as @klauspost. The overclass is no longer removed when I drop outside of the target. It happens for me on Chrome, Firefox, and Safari.

**Comment by Falldog** [comment]
@jackhsu978 me too

**Comment by jackhsu978** [comment]
@Falldog you may be interested in [this workaround](https://github.com/nervgh/angular-file-upload/issues/231#issuecomment-154403916).

**Pull request merged**
