### PR TITLE
Updated the gulp /build task to export both uglified and normal version

### PR DESCRIPTION
**Pull request by andrei-cacio**
This pull request fixes the #526 issue.

I've created 2 separate `webpack streams` and 2 separate `gulp streams` for both uglified and normal version of the file exported. A simple stream concat solved the problem and now there are both versions available in the `dist` folder.

### CODE REVIEW

**Comment by nervgh** [comment]
@andrei-cacio , thanks :thumbsup: But I think more elegant way [that](https://github.com/nervgh/angular-file-upload/issues/526#issuecomment-145819564). Then we and other developers can write something like this 
```js
gulp.task(
    pkg.name + '/build',
    function() {
        var MODULE = {
            loaders: [
                // https://github.com/babel/babel-loader
                {test: /\.js$/, loader: 'babel'},
                // https://github.com/webpack/json-loader
                {test: /\.json$/, loader: 'json'},
                // https://github.com/webpack/html-loader
                {test: /\.html$/, loader: 'html'}
            ]
        };
        // http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
        var UGLIFY = new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        });
        // http://webpack.github.io/docs/list-of-plugins.html#bannerplugin
        var BANNER = new webpack.BannerPlugin(
            '/*\n' +
            ' ' + pkg.name + ' v' + pkg.version + '\n' +
            ' ' + pkg.homepage + '\n' +
            '*/\n'
            ,
            {
                entryOnly: true,
                raw: true
            }
        );

        return gulp
            .src('./src/index.js')
            .pipe(webpackStream(
                [
                    // full
                    {
                        module: MODULE,
                        plugins: [BANNER],
                        devtool: 'source-map',
                        output: {
                            library: pkg.name,
                            libraryTarget: 'umd',
                            filename: pkg.name + '.js'
                        }
                    },
                    // min
                    {
                        module: MODULE,
                        plugins: [UGLIFY, BANNER],
                        devtool: 'source-map',
                        output: {
                            library: pkg.name,
                            libraryTarget: 'umd',
                            filename: pkg.name + '.min.js'
                        }
                    }
                ]
            ))
            .pipe(gulp.dest('./dist'));
    }
);
```
without additional dependencies. What is your opinon?

**Comment by andrei-cacio** [comment]
yes, I didn't thought of multiple web socket streams in a single array. Your version is definitely better. I will update my PR

**Comment by andrei-cacio** [comment]
hmm, although, it doesn't seem to work this way. It doesn't output anything

**Comment by andrei-cacio** [comment]
Look into the `webpack-stream` package at the [function](https://github.com/shama/webpack-stream/blob/master/index.js#L26-27) exported, the `options` param is treated as an object. Am I missing something?

**Comment by andrei-cacio** [comment]
is this a good compromise? We only use the `event-stream` plugin to concat the new streams

```
gulp.task(
    pkg.name + '/build',
    function() {
        var MODULE = {
            loaders: [
                // https://github.com/babel/babel-loader
                {test: /\.js$/, loader: 'babel'},
                // https://github.com/webpack/json-loader
                {test: /\.json$/, loader: 'json'},
                // https://github.com/webpack/html-loader
                {test: /\.html$/, loader: 'html'}
            ]
        };
        // http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
        var UGLIFY = new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        });
        // http://webpack.github.io/docs/list-of-plugins.html#bannerplugin
        var BANNER = new webpack.BannerPlugin(
            '/*\n' +
            ' ' + pkg.name + ' v' + pkg.version + '\n' +
            ' ' + pkg.homepage + '\n' +
            '*/\n'
            ,
            {
                entryOnly: true,
                raw: true
            }
        );

        var normalStream =
            gulp
                .src('./src/index.js')
                .pipe(webpackStream({
                    module: MODULE,
                    plugins: [BANNER],
                    devtool: 'source-map',
                    output: {
                        library: pkg.name,
                        libraryTarget: 'umd',
                        filename: pkg.name + '.js'
                    }
                }))
                .pipe(gulp.dest('./dist'));

        var uglifyStream =
            gulp
                .src('./src/index.js')
                .pipe(webpackStream({
                    module: MODULE,
                    plugins: [BANNER, UGLIFY],
                    devtool: 'source-map',
                    output: {
                        library: pkg.name,
                        libraryTarget: 'umd',
                        filename: pkg.name + '.min.js'
                    }
                }))
                .pipe(gulp.dest('./dist'));

        return es.concat(normalStream, uglifyStream);
    }
);
```
@nervgh

**Comment by nervgh** [comment]
@andrei-cacio 

> But I think more elegant way [that](https://github.com/nervgh/angular-file-upload/issues/526#issuecomment-145819564).
https://github.com/nervgh/angular-file-upload/pull/532#issuecomment-149499481

I did mean what If you have time and motivation for implementation of [multi-compiler feature](https://github.com/shama/webpack-stream/issues/78) in the webpack-stream project then it will be great, otherwise I can merge your current PR.
First variant is prefered because we and other developers could be use it in other projects "out of the box".

**Comment by andrei-cacio** [comment]
@nervgh 

about the multi-compiler feature, I will try to open a PR for that but I cannot promise anything. Meanwhile if the actual PR version is ok with you, I'm fine for it to be merged. Should I remove both **minified** and **normal** files from the PR?

**Comment by nervgh** [comment]
> Should I remove both minified and normal files from the PR?
https://github.com/nervgh/angular-file-upload/pull/532#issuecomment-150141020

1)
> Please, exclude `dist/` files
https://github.com/nervgh/angular-file-upload/pull/532#issuecomment-149984568

```
dist/angular-file-upload.js
dist/angular-file-upload.js.map
dist/angular-file-upload.min.js
dist/angular-file-upload.min.js.map
```

2) to format `package.json` with previous [code style](https://github.com/andrei-cacio/angular-file-upload/commit/e4ba665da3df6b97c1759afb8ccc2d2b0a51c727#diff-5)

**Comment by andrei-cacio** [comment]
@nervgh I've reverted the `dist` folder and reverted the code style

**Comment by andrei-cacio** [comment]
@nervgh also what do you think about #537 ?

**Comment by nervgh** [comment]
@andrei-cacio , good job, thanks! :+1:

**Pull request merged**
