### PR TITLE
Added support to upload files without multipart (HTML5 only)

### PR DESCRIPTION
**Pull request by josencv**
For those who have problems uploading to Amazon S3 with pre-signed urls, use this:

```javascript
var uploader = new FileUploader({disableMultipart: true});
```

And there you go.

### CODE REVIEW

**Comment by poupougnac** [comment]
I found out an issue with Chrome (Version 50.0.2661.49 beta (64-bit)), it appears that I need to use the native File object instead of FileLikeObject. Otherwise, it sends this payload : [Object object]

For people having this issue : I had to edit this line in order to make my upload on S3 to work :
```
if (!item.disableMultipart) {
   ...
            }
            else {
                //old
                //sendable = item.file;
                //new
                sendable = item._file;
            }
}
```

**Comment by nervgh** [comment]
@josencv , please remove bundled files from PR (angular-file-upload & angular-file-upload.min)

**Comment by josencv** [comment]
Should I remove the map files?

Also, should I remove them (git rm <file>), or should I leave the version cloned from your repo?

**Comment by nervgh** [comment]
You could include in you PR all files except files in `/dist` folder, because that folder contains few bundled files (*.js, *.map, etc). Those files contains some specific data like [a version number](https://github.com/nervgh/angular-file-upload/blob/master/dist/angular-file-upload.js#L2). These data could be change when will the release.

**Comment by josencv** [comment]
Done.

P.S: I checked out the @poupougnac bug but when I tried his solution the files uploaded to Amazon S3 got corrupted. Don't work for me so I won't add it to this PR. Maybe the problem is related to the content type header sent to Amazon?

**Comment by jercoh** [comment]
I encountered the same issue as @poupougnac. 
His solution worked for me as well without corrupting the file. 
I think it's worth investing this.

**Comment by josencv** [comment]
Ok. Does anyone have time to investigate this? I don't have much time.

@poupougnac do you think it has something to do with the chrome version? I think it may be the content-type header (I sign the url with the image content type as the 'content-type' header, and then make a PUT request to the signed url with the same content type). It's just a quick theory though,

**Comment by josencv** [comment]
Sorry, @poupougnac fix was right. I mistakenly used the original release files instead of the fixed one. Added the fix to this PR.

**Comment by nervgh** [comment]
@josencv thank you for your contribution :v:

**Pull request merged**
